version: '3.9'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    expose:
      - 5432
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web
      - db

volumes:
  postgres_data_prod:
